### ISSUE TITLE
Cannot build project with wiredash 2.3.0 and Flutter 3.29.0

### ISSUE THREAD

**Issue by gibahjoe** [wiredashio/wiredash-sdk#377]
**Describe the bug**
There is a breaking change on `widgetInspector` in flutter 3.29.0. `selectButtonBuilder` was removed and `exitWidgetSelectionButtonBuilder`, `moveExitWidgetSelectionButtonBuilder` was added. This is causing builds to fail. 

**Stacktrace**
```sh
../../../../../.pub-cache/hosted/pub.dev/wiredash-2.3.0/lib/src/core/support/not_a_widgets_app.dart:37:9: Error: No named parameter with the name 'selectButtonBuilder'.
        selectButtonBuilder: (BuildContext context, void Function() onPressed) {
        ^^^^^^^^^^^^^^^^^^^
../../../../tools/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:2772:9: Context: Found this candidate, but the arguments don't match.
  const WidgetInspector({
        ^^^^^^^^^^^^^^^
```

**Wiredash SDK Info**
2.3.0 on MacOS, Windows

**Flutter SDK**
3.29.0

**Screenshots**
N/A

**Comment by passsy** [comment]
The fix has already been [merged](https://github.com/wiredashio/wiredash-sdk/pull/373). You can use it right away using

```yaml
dependencies:
  wiredash:
    git:
      url: https://github.com/wiredashio/wiredash-sdk.git
      ref: d670bd743a5dd47e0b8cedd47b55e9a7a65cf01b
```

Official release will happen later today
